//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SII_Entities : DbContext
    {
        public SII_Entities()
            : base("name=SII_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Tbl_Acta> Tbl_Acta { get; set; }
        public virtual DbSet<Tbl_Acta_Usuario> Tbl_Acta_Usuario { get; set; }
        public virtual DbSet<Tbl_Agremiado> Tbl_Agremiado { get; set; }
        public virtual DbSet<Tbl_Compania> Tbl_Compania { get; set; }
        public virtual DbSet<Tbl_Deduccion> Tbl_Deduccion { get; set; }
        public virtual DbSet<Tbl_Departamento> Tbl_Departamento { get; set; }
        public virtual DbSet<Tbl_Empleado> Tbl_Empleado { get; set; }
        public virtual DbSet<Tbl_EstadoCivil> Tbl_EstadoCivil { get; set; }
        public virtual DbSet<Tbl_Gestion> Tbl_Gestion { get; set; }
        public virtual DbSet<Tbl_Persona> Tbl_Persona { get; set; }
        public virtual DbSet<Tbl_Rol> Tbl_Rol { get; set; }
        public virtual DbSet<Tbl_TipoGestion> Tbl_TipoGestion { get; set; }
        public virtual DbSet<Tbl_TipoUsuario> Tbl_TipoUsuario { get; set; }
        public virtual DbSet<Tbl_Usuario> Tbl_Usuario { get; set; }
        public virtual DbSet<Tbl_Pais> Tbl_Pais { get; set; }
        public virtual DbSet<Tbl_Bit_Ingreso> Tbl_Bit_Ingreso { get; set; }
        public virtual DbSet<Tbl_ActasPDF> Tbl_ActasPDF { get; set; }
        public virtual DbSet<Tbl_NoticiasPDF> Tbl_NoticiasPDF { get; set; }
    }
}
