//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Acta_Usuario
    {
        public int id_A_U { get; set; }
        public int id_Acta { get; set; }
        public int id_Usuario { get; set; }
    
        public virtual Tbl_Acta Tbl_Acta { get; set; }
        public virtual Tbl_Usuario Tbl_Usuario { get; set; }
    }
}
