//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Bit_Ingreso
    {
        public int id { get; set; }
        public Nullable<long> usuario { get; set; }
        public Nullable<System.DateTime> hora { get; set; }
        public Nullable<int> rol { get; set; }
    }
}
