//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_ActasPDF
    {
        public int id_Acta { get; set; }
        public System.DateTime fecha_Creacion_A { get; set; }
        public string titulo_Acta { get; set; }
        public string subtitulo_Acta { get; set; }
        public string contenido_Acta { get; set; }
        public Nullable<int> estado { get; set; }
    }
}
