//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Sindicato_v1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Usuario
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tbl_Usuario()
        {
            this.Tbl_Acta_Usuario = new HashSet<Tbl_Acta_Usuario>();
            this.Tbl_Agremiado = new HashSet<Tbl_Agremiado>();
            this.Tbl_Empleado = new HashSet<Tbl_Empleado>();
        }
    
        public int id_Usuario { get; set; }
        public int id_Persona { get; set; }
        public string contrasenia { get; set; }
        public int id_Rol { get; set; }
        public int id_TipoUsu { get; set; }
        public int estado { get; set; }
        public string token_recovery { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Acta_Usuario> Tbl_Acta_Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Agremiado> Tbl_Agremiado { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tbl_Empleado> Tbl_Empleado { get; set; }
        public virtual Tbl_Persona Tbl_Persona { get; set; }
        public virtual Tbl_Rol Tbl_Rol { get; set; }
        public virtual Tbl_TipoUsuario Tbl_TipoUsuario { get; set; }
    }
}
